In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import xgboost as xgb
from joblib import dump, load
from xgboost import XGBClassifier
from sklearn.inspection import permutation_importance
# import eli5
# from eli5.sklearn import PermutationImportance

In [34]:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [35]:
#Data reading, data cleaning
data = pd.read_csv('dataset.csv',sep = ';') 
data = data.replace('unknown', np.nan)

In [36]:
#categoricat variables
data['education'] = data['education'].fillna(data['education'].mode()[0])
data['job'] = data['job'].fillna(data['job'].mode()[0])
data['marital'] = data['marital'].fillna(data['marital'].mode()[0])
data['housing'] = data['housing'].fillna(data['housing'].mode()[0])
data['default'] = data['default'].fillna(data['default'].mode()[0])

In [37]:
#mean encoder
data['y'].replace({"no":0, "yes":1}, inplace=True)

Mean_encoded_job = data.groupby(['job'])['y'].mean().to_dict()   
data['job'] =  data['job'].map(Mean_encoded_job) 

Mean_encoded_marital = data.groupby(['marital'])['y'].mean().to_dict()   
data['marital'] =  data['marital'].map(Mean_encoded_marital) 

Mean_encoded_default = data.groupby(['default'])['y'].mean().to_dict()   
data['default'] =  data['default'].map(Mean_encoded_default)

Mean_encoded_housing = data.groupby(['housing'])['y'].mean().to_dict()   
data['housing'] =  data['housing'].map(Mean_encoded_housing)

Mean_encoded_loan = data.groupby(['loan'])['y'].mean().to_dict()   
data['loan'] =  data['loan'].map(Mean_encoded_loan)

Mean_encoded_contact = data.groupby(['contact'])['y'].mean().to_dict()   
data['contact'] =  data['contact'].map(Mean_encoded_contact)

Mean_encoded_month = data.groupby(['month'])['y'].mean().to_dict()   
data['month'] =  data['month'].map(Mean_encoded_month)

Mean_encoded_poutcome = data.groupby(['poutcome'])['y'].mean().to_dict()   
data['poutcome'] =  data['poutcome'].map(Mean_encoded_poutcome)

Mean_encoded_day_of_week = data.groupby(['day_of_week'])['y'].mean().to_dict()   
data['day_of_week'] =  data['day_of_week'].map(Mean_encoded_day_of_week)
 
Mean_encoded_education = data.groupby(['education'])['y'].mean().to_dict()   
data['education'] =  data['education'].map(Mean_encoded_education)

In [38]:
data_drop = pd.DataFrame()
data_drop = data
data_drop.fillna(data_drop.mean(), inplace = True)

In [39]:
#train test split
y = data_drop[['y']]
X = data_drop.drop(['y'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

clf = xgb.XGBClassifier(max_depth=5, n_estimators=100 ,class_weight='balanced', n_jobs=-1)
clf.fit(X_train.to_numpy(), y_train.to_numpy())

[20:36:39] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480:
Parameters: { class_weight } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.

XGBClassifier(base_score=0.5, booster='gbtree', class_weight='balanced',
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              gamma=0, gpu_id=-1, importance_type='gain',
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=5, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=-1,
              num_parallel_tree=1, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [40]:
X_train.to_numpy()

array([[ 3.00000000e+01,  6.89431597e-02,  1.01727447e-01, ...,
        -4.62000000e+01,  1.29900000e+00,  5.09910000e+03],
       [ 5.80000000e+01,  8.13807004e-02,  1.01727447e-01, ...,
        -3.48000000e+01,  6.35000000e-01,  5.00870000e+03],
       [ 3.20000000e+01,  6.89431597e-02,  1.03209020e-01, ...,
        -4.27000000e+01,  4.96300000e+00,  5.22810000e+03],
       ...,
       [ 3.60000000e+01,  6.89431597e-02,  1.01727447e-01, ...,
        -3.64000000e+01,  4.85700000e+00,  5.19100000e+03],
       [ 3.70000000e+01,  1.29185268e-01,  1.01727447e-01, ...,
        -4.27000000e+01,  4.95500000e+00,  5.22810000e+03],
       [ 3.50000000e+01,  6.89431597e-02,  1.40041494e-01, ...,
        -4.62000000e+01,  1.29900000e+00,  5.09910000e+03]])

In [41]:
import pickle
pickle.dump(clf, open("model.dat", "wb"))

In [42]:
loaded_model = pickle.load(open("model.dat", "rb"))

In [44]:
loaded_model.predict(X_test.to_numpy())

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [45]:
X_test

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
35577,32,0.068943,0.101727,0.078246,0.112662,0.115838,0.109315,0.147376,0.064347,0.099483,114,1,999,0,0.088322,-1.8,92.893,-46.2,1.244,5099.1
13950,33,0.068943,0.140041,0.082024,0.112662,0.115838,0.109315,0.147376,0.090466,0.108087,103,2,999,0,0.088322,1.4,93.918,-42.7,4.963,5228.1
29451,25,0.104856,0.103209,0.138211,0.112662,0.115838,0.113402,0.147376,0.204787,0.099483,227,5,999,0,0.088322,-1.8,93.075,-47.1,1.405,5099.1
32295,34,0.068943,0.140041,0.108355,0.112662,0.115838,0.113402,0.147376,0.064347,0.108087,56,1,999,0,0.088322,-1.8,92.893,-46.2,1.313,5099.1
27477,53,0.108260,0.101727,0.113485,0.112662,0.115838,0.113402,0.147376,0.101439,0.108087,11,7,999,0,0.088322,-0.1,93.200,-42.0,4.021,5195.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8337,30,0.081381,0.101727,0.108355,0.112662,0.108796,0.109315,0.052313,0.105115,0.117800,220,1,999,0,0.088322,1.4,94.465,-41.8,4.864,5228.1
29097,38,0.108260,0.101727,0.113485,0.112662,0.108796,0.113402,0.147376,0.204787,0.108087,1624,1,999,2,0.142286,-1.8,93.075,-47.1,1.405,5099.1
30687,32,0.068943,0.101727,0.078246,0.112662,0.115838,0.113402,0.147376,0.064347,0.117800,72,1,999,2,0.142286,-1.8,92.893,-46.2,1.344,5099.1
33048,46,0.068943,0.101727,0.102490,0.112662,0.108796,0.113402,0.052313,0.064347,0.099483,338,2,999,0,0.088322,-1.8,92.893,-46.2,1.299,5099.1
24024,30,0.108260,0.140041,0.138211,0.112662,0.108796,0.113402,0.052313,0.438719,0.116671,676,1,999,0,0.088322,-0.1,93.798,-40.4,4.936,5195.8

In [46]:
for element in X_test:
    print(element)

age
job
marital
education
default
housing
loan
contact
month
day_of_week
duration
campaign
pdays
previous
poutcome
emp.var.rate
cons.price.idx
cons.conf.idx
euribor3m
nr.employed

In [47]:
tt = np.array([[32,0.068943,0.101727,0.078246,0.112662,0.115838,0.109315,0.147376,0.064347,0.099483,114,1,999,0, 0.088322,-1.8,92.893,-46.2,1.244,5099.1]])

In [48]:
loaded_model.predict(tt)

array([0], dtype=int64)